// <auto-generated />
namespace PBLCopos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _12042019final : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_12042019final));
        
        string IMigrationMetadata.Id
        {
            get { return "201904120808590_12042019final"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
